spring.application.name=backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bachelors_kitchen
spring.datasource.username=bk_user
spring.datasource.password=bk_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
